name: Build and Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build:all
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            grx.dmg
            grx-setup.exe
            grx.AppImage
            grx.snap
            grx.deb
